### ISSUE TITLE
现在的代码谁在维护啊

### ISSUE THREAD

**Issue by crab2313** [kernelhcy/gtkqq#108]
有个bug， 看见修一下，
还有那个 qqpoll， 为什么要新开一个线程， 既然用了glib，
可以用g_idle_add(), 将那个函数挂到loop里，

**Comment by mathslinux** [comment]
@crab2313 你可以提交 patch, 也可以参与新版本的开发.

**Comment by crab2313** [comment]
好 @mathslinux
