### ISSUE TITLE
请添加m4目录

### ISSUE THREAD

**Issue by leaeasy** [kernelhcy/gtkqq#12]
编译时提示无m4目录，需要手动创建m4目录来进行编译

**Comment by shwangdev** [comment]
应该不要的，我回头找几个packager帮忙打包。
On Dec 3, 2011 11:51 AM, "Li Longyu" <
reply@reply.github.com>
wrote:

**Comment by mathslinux** [comment]
直接运行 ./autogen.sh && ./configure && make && make install 就可以了
m4 是 配置编译环境过程中(configure)自动生成的.

**Comment by shwangdev** [comment]
just close it .
