### ISSUE TITLE
bad support with GNOME3

### ISSUE THREAD

**Issue by ekd123** [kernelhcy/gtkqq#17]
can't use input method.

GTK2 app is ugly in GNOME3. Please use GTK3 instead.

Platform: Arch Linux x86_64
DE: GNOME 3.2

**Comment by ekd123** [comment]
PS: avatar and member list of a group can't be shown!

**Comment by mathslinux** [comment]
@ekd123 There is no input method error on my system. i have test it on gentoo amd-64 with gnome3.2 installed, and fedora 64 with gnome32 installed,

**Comment by ekd123** [comment]
@mathslinux well, in fact, i want a gtkqq version with GTK+3! I think that will make gtkqq more beautiful~

**Comment by mathslinux** [comment]
@ekd123 Ok, i will think of your suggestion later.

**Comment by ekd123** [comment]
close..
