### ISSUE TITLE
不能通过编译！

### ISSUE THREAD

**Issue by chenyj** [kernelhcy/gtkqq#2]
UBUNTU 11.10环境下编译不能通过，提示错误如下：

testhttp.c
testhttp.c: 在函数‘main’中:
testhttp.c:44:2: 错误： 格式字符串不是一个字面字符串而且没有待格式化的实参 [-Werror=format-security]
cc1：所有的警告都被当作是错误

make[3]: **\* [testhttp.o] 错误 1
make[3]:正在离开目录 `/home/chenyj/Downloads/gtkqq/src/test'
make[2]: *** [all-recursive] 错误 1
make[2]:正在离开目录`/home/chenyj/Downloads/gtkqq/src'
make[1]: **\* [all-recursive] 错误 1
make[1]:正在离开目录 `/home/chenyj/Downloads/gtkqq'
make: **\* [all] 错误 2

**Comment by ekd123** [comment]
干掉-Werror参数即可。

**Comment by kernelhcy** [comment]
Gtkqq已经停滞开发很长时间了。目前很不完善。如果感兴趣，欢迎加入开发。

**Comment by chenyj** [comment]
谢谢，已经通过编译了！但是运行gtkqq的时候又出现错误：

*\* ERROR **: Open database error. unable to open database file (dao.c, 89)
跟踪/断点陷阱

我技术不行，只能帮忙测试一下！

**Comment by ekd123** [comment]
我也是相同的错误，能编译但打不开。

**Comment by ekd123** [comment]
话说最新的commit在4天前，不算是停滞很长时间吧？

**Comment by kernelhcy** [comment]
最新的commit只是删除了一些文件。不算开发。

**Comment by shwangdev** [comment]
*\* ERROR **: Open database error. unable to open database file (dao.c, 89)

这是个bug,我已经修复了。

**Comment by chenyj** [comment]
如何修复的？

**Comment by shwangdev** [comment]
创建DB在创建默认.~/.gtkqq目录之前，而db又是放在~/.gtkqq目录下面的。
我把顺序改了下就可以了。
