### ISSUE TITLE
program crash at qqlogin.c

### ISSUE THREAD

**Issue by xyubuntu** [kernelhcy/gtkqq#22]
The size of array params is too small and overwriting it  may smash the stack of function get_ptcz_skey().
I modify 300 to 500 to sovle the problem.

**Comment by mathslinux** [comment]
@xyubuntu The code here is g_sprintf(...); Normally it should use g_snprintf, not g_sprintf. and the size of the params is small, i will fix those bugs. thanks.

**Comment by ekd123** [comment]
@mathslinux well.. a better way is to use gstring instead.
