### ISSUE TITLE
Syntax still error @gui/gqqconfig.c

### ISSUE THREAD

**Issue by wanderxjtu** [kernelhcy/gtkqq#23]
Same with issue #20/21，#21 seems to fix the compile failure, but  I think that ')' should be right after 'G_FILE_TEST_EXISTS' to close the 'g_file_test' function.

diff --git a/src/gui/gqqconfig.c b/src/gui/gqqconfig.c
index 7796514..ea56614 100644
--- a/src/gui/gqqconfig.c
+++ b/src/gui/gqqconfig.c
@@ -241,8 +241,8 @@ static void gqq_config_init(GQQConfig *self)
 {
     GString *cfgdir = g_string_new (g_get_home_dir ());
     g_string_append (cfgdir, "/.gtkqq");
-    if(!g_file_test(cfgdir->str, G_FILE_TEST_EXISTS
-       && -1 == g_mkdir(cfgdir->str, 0777))){
-    if(!g_file_test(cfgdir->str, G_FILE_TEST_EXISTS)
-       && -1 == g_mkdir(cfgdir->str, 0777)){
       g_error("Create config dir %s error!(%s, %d)"
               , cfgdir->str, **FILE**, **LINE**);
   }

**Comment by shwangdev** [comment]
bug fix.
