### ISSUE TITLE
无法和windows上的QQ用户聊天

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#26]
可以和webqq用户互聊，也可以接受来自windows上的QQ用户的信息，但是向windows的qq发送信息时，对方收不到。

可以用 debug 调试吗？该看哪部分信息？

**Comment by shwangdev** [comment]
不可能吧。 接受消息部分是用的http长连接，你可以抓包看看长连接还发出去了。

2011/12/16 billzt
reply@reply.github.com:

> 可以和webqq用户互聊，也可以接受来自windows上的QQ用户的信息，但是向windows的qq发送信息时，对方收不到。
> 
> 可以用 debug 调试吗？该看哪部分信息？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/26

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@wxjeacen 可是具体该怎么操作呢？

**Comment by shwangdev** [comment]
我刚刚测试了下，可以work的啊。
