### ISSUE TITLE
好友信息变化不及时

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#27]
与好友聊天之后，好友离线，但是状态列表里却一直显示是在线的。这样子就容易误导了。有没有办法对方下线之后我这里就立即显示离线？

**Comment by shwangdev** [comment]
允许有时间差的吧。

2011/12/20 billzt
reply@reply.github.com:

> 与好友聊天之后，好友离线，但是状态列表里却一直显示是在线的。这样子就容易误导了。有没有办法对方下线之后我这里就立即显示离线？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/27

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@wxjeacen 差太多了，我是把 gtkqq 与 webqq 同步测试的，现在快十分钟过去了 gtkqq 还没有任何变化（我估计它是永远都不会变了），webqq 基本上不超过几秒钟。
有什么办法能够 debug？我可以帮你下

**Comment by shwangdev** [comment]
wireshark抓 webqq的包，看看logout的时候丢了哪个http 包。

2011/12/20 billzt
reply@reply.github.com:

> @wxjeacen 差太多了，我是把 gtkqq 与 webqq 同步测试的，现在快十分钟过去了 gtkqq 还没有任何变化（我估计它是永远都不会变了），webqq 基本上不超过几秒钟。
> 有什么办法能够 debug？我可以帮你下
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/27#issuecomment-3213407

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@wxjeacen 这个不会操作啊，还是呼唤大牛过来帮忙吧。刚又试了一遍，还是存在问题

**Comment by tao-bioinfo** [comment]
另外好友上线了，gtkqq里也没有显示，还是一直离线的

**Comment by mathslinux** [comment]
@billzt  @wxjeacen 这个信息是可以抓到的, 好友上线和离线的时候其实代码那里已经有了, 只是没有变化而已. 我之前加声音提示的时候好友上线用的就是之前的 code . 等等明天我找时间加进去.

**Comment by tao-bioinfo** [comment]
@mathslinux 呵呵，多谢关注哈

**Comment by mathslinux** [comment]
@billzt @wxjeacen patch 我已经提交. https://github.com/mathslinux/gtkqq/commit/a5dda08ccc184d9e7a12e8987301c86bc52e88ca

**Comment by tao-bioinfo** [comment]
@mathslinux 测试成功！十分感谢！
