### ISSUE TITLE
各种使用问题

### ISSUE THREAD

**Issue by cuihaoleo** [kernelhcy/gtkqq#3]
第一个：
编译出来两个可执行文件，一个gtkqq，一个qq，那个qq不知道是干啥的，用不了。

信息好像发送不出去。有WARNING：
*\* WARNING *\* : Unknown message type: 0 (qqsendmsg.c, 211)
*\* WARNING *\* : Send message error!!  (groupchatwindow.c, 314)

有时候会崩溃：
*\* WARNING *\* : Read data ERROR!! code:8 msg:Connection reset by peer(url.c, 292)
[1]    3293 segmentation fault  gtkqq

我没编译test部分的代码，没啥影响吧？

**Comment by ekd123** [comment]
同样的错误。无法发出消息。无法获得群成员和简介。无法获得正确的头像。希望尽快更新协议。

**Comment by shwangdev** [comment]
*我看下先，我貌似编译出一个binary文件。
*
2011/11/12 cuihaoleo <
reply@reply.github.com

> 第一个：
> 编译出来两个可执行文件，一个gtkqq，一个qq，那个qq不知道是干啥的，用不了。
> 
> 信息好像发送不出去。有WARNING：
> *\* WARNING *\* : Unknown message type: 0 (qqsendmsg.c, 211)
> *\* WARNING *\* : Send message error!!  (groupchatwindow.c, 314)
> 
> 有时候会崩溃：
> *\* WARNING *\* : Read data ERROR!! code:8 msg:Connection reset by
> peer(url.c, 292)
> [1]    3293 segmentation fault  gtkqq
> 
> 我没编译test部分的代码，没啥影响吧？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/3

## 

**
*

Best Regards,
**

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com wxjeacen@gmail.com

*

**Comment by cuihaoleo** [comment]
64位Arch，用自己写的PKGBUILD编译的。摘取编译部分：
sed -i "s/test//" src/Makefile.am
sed -i "s/-Werror//" src/libqq/Makefile.am
sed -i "s/-Werror//" src/gui/Makefile.am
./autogen.sh
./configure --prefix=/usr --disable-debug
make
make DESTDIR=${pkgdir}/ install

安装的文件列表：
http://pastebin.com/9kWrPqJ5

**Comment by shwangdev** [comment]
./src/gui/gtkqq 
*\* WARNING *\* : Unknown message type: 0 (qqsendmsg.c, 211)
*\* WARNING *\* : Send message error!!  (chatwindow.c, 98)
*\* WARNING *\* : No such name raw_content!(qqpoll.c, 22)

似乎qq_send_message 函数有点问题，我回头看看。

**Comment by shwangdev** [comment]
我修掉这个bug了。是因为在构造QQ_Send_Message的时候，没有指定type.所以才找不到message的类型。

而且在free err指针之前没有判断NULL,我已经commit code了。麻烦在测试下看看。

**Comment by ekd123** [comment]
希望能有一个aur啊！自己下没有包管理还是麻烦了点。

现在可以收到、发出消息，不过还是看不到头像、成员列表，群内成员的昵称也显示不出来。。

**Comment by shwangdev** [comment]
God bless,我这里一直都在公司里面，需要proxy认证。而gtkqq没有proxy 选项。

我只是试着看source code,从你们 provided log里面去改代码。。
看来还是 work了。

**Comment by cuihaoleo** [comment]
挺容易崩溃的：

DEBUG : Msg Content: string 和1080P區別大嗎？ (qqpoll.c, 80)
DEBUG : Msg Content: font 宋体 9 000000 000(qqpoll.c, 134)
DEBUG : Msg Content: string 23 led   (qqpoll.c, 80)
DEBUG : poll.(qqpoll.c, 304)
[1]    21175 segmentation fault  gtkqq

DEBUG : Get qq number.(qqmanageinfo.c, 41)
DEBUG : Content-Length: 71.(url.c, 318)
DEBUG : qq number: ?????????? (qqmanageinfo.c, 101)
DEBUG : Get online buddies!(qqmanageinfo.c, 208)
[1]    23095 segmentation fault  gtkqq

DEBUG : Content-Length: 73.(url.c, 318)
DEBUG : qq number: ?????????? (qqmanageinfo.c, 101)
DEBUG : Get qq number.(qqmanageinfo.c, 41)
DEBUG : Content-Length: 88.(url.c, 318)
DEBUG : qq number: ?????????? (qqmanageinfo.c, 101)
DEBUG : Get qq number.(qqmanageinfo.c, 41)
[1]    13259 segmentation fault  gtkqq

@ekd123：
刚传的： https://aur.archlinux.org/packages.php?ID=53978

**Comment by kernelhcy** [comment]
gtkqq是编译后的执行文件。qq仅仅是用来测试gtk用的，没什么用处。

**Comment by kernelhcy** [comment]
这个项目停止了很久了，qq的协议估计更新了。目前我没有多少精力可以放在这个上。

**Comment by shwangdev** [comment]
_我稍微看了下，可能改的地方不是很多。_
*现在应该基本的 发送和接受message是没问题的。 我做了部分的修改。
*
2011/11/14 HuangCongyu <
reply@reply.github.com

> 这个项目停止了很久了，qq的协议估计更新了。目前我没有多少精力可以放在这个上。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/3#issuecomment-2726928

## 

**
*

Best Regards,
**

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com wxjeacen@gmail.com

*
