### ISSUE TITLE
建议在项目主页上把编译时需要安装的工具包列出来

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#30]
有人说 ./autogen.sh 就发生错误，./autogen.sh: 行 4: aclocal: 未找到命令，其实是没安装执行 aclocal 所必需的软件包。

作者把需要安装的工具包列一列吧！要别人一个一个地去尝试会很痛苦的

**Comment by shwangdev** [comment]
哪需要这么麻烦，到时候直接做成rpm就好了。

已经有人做好了spec,我在review.

2011/12/21 billzt
reply@reply.github.com:

> 有人说 ./autogen.sh 就发生错误，./autogen.sh: 行 4: aclocal: 未找到命令，其实是没安装执行 aclocal 所必需的软件包。
> 
> 作者把需要安装的工具包列一列吧！要别人一个一个地去尝试会很痛苦的
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/30

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@wxjeacen 已经有人打包了？不错，但是打包也得先打 deb 啊，ubuntu/mint 的庞大用户群不是可以无视掉的。或者你可以在这个 issue 里说一下，我去转告别人也行。

**Comment by tao-bioinfo** [comment]
已经摸索出
