### ISSUE TITLE
bug: 群聊天时成员显示的名称有误

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#31]
群聊天时应该显示成员的昵称或备注，但据有人测试显示：现在显示的是一个陌生的号码，而且所有人显示的都是同一个陌生的号码。这个 bug 比较纠结，建议早点修复。

截图可见 http://forum.ubuntu.org.cn/viewtopic.php?f=73&t=358133 第22楼

**Comment by shwangdev** [comment]
这个问题我曾经 研究过。

未果。

2011/12/22 billzt
reply@reply.github.com:

> 群聊天时应该显示成员的昵称或备注，但据有人测试显示：现在显示的是一个陌生的号码，而且所有人显示的都是同一个陌生的号码。这个 bug 比较纠结，建议早点修复。
> 
> 截图可见 http://forum.ubuntu.org.cn/viewtopic.php?f=73&t=358133 第22楼
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/31

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by mathslinux** [comment]
@billzt @wxjeacen 这个问题已经解决了, 在我的 fork branch 上, 由于我上次 pull 的 request的还没有被 merge, 所以现在暂时不能 pull request, 你可以到我的 fork 的分支上 clone. https://github.com/mathslinux/gtkqq

PS. 刚开始打开聊天窗口的时候, 获取群成员比较慢, 所以开始信息可能不会对.但是只要成员列表刷出来就可以了正确了. 我看了一下相关代码, 是从数据库读的数据, 开始的时候, 但是 damn it, glib 的event 太fuck了, 可能没有处理好, 相关修改我以后再看看.

**Comment by tao-bioinfo** [comment]
@mathslinux 谢谢哈，动作好快！

**Comment by shwangdev** [comment]
just close it
