### ISSUE TITLE
bug：dao.c 80～82行有点问题

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#32]
我在自己电脑上编译了deb包，没有问题。然后使用 launchpad 上的ppa编译了deb包，运行出问题了：

DEBUG : Open db connection to /home/buildd/.gtkqq/gtkqq.db (dao.c, 81)

*\* ERROR **: Open database error. unable to open database file (dao.c, 89)
跟踪/断点陷阱

额，我的电脑上并没有 /home/buildd 这种目录啊！看了下 dao.c 80~82 行：

```
g_debug("Open db connection to "CONFIGDIR"gtkqq.db (%s, %d)"
                                    , __FILE__, __LINE__);
gint retcode = sqlite3_open(CONFIGDIR"gtkqq.db", &db);
```

这个 CONFIGDIR 变量是否有点问题？我觉得应该取用户的家目录，而不能取编译目录。事实上，/home/buildd 这个目录是我在launchpad虚拟平台上编译时的目录，编译完了是要给其它人使用的

**Comment by mathslinux** [comment]
@billzt have solved, see https://github.com/kernelhcy/gtkqq/pull/33

**Comment by tao-bioinfo** [comment]
@mathslinux 在链接中 ekd123 指出可能存在 mem leak？这个比较危险，我再等等看？

**Comment by mathslinux** [comment]
@billzt @ekd123 仔细看我的代码,  static GString *facedir = NULL; facedir是 static 类型的, 
只有第一次的时候才会进去        facedir = g_string_new(gqq_config_get_cfgdir());

我就是不想每次都 new 才用 static 变量的. 代码并没有问题.

**Comment by tao-bioinfo** [comment]
@mathslinux 没关系，只要不影响内存占用就行，我安装试试看

**Comment by ekd123** [comment]
it's my mistake... go merging it~

**Comment by tao-bioinfo** [comment]
问题已解决
