### ISSUE TITLE
autogen.sh时出错。。。

### ISSUE THREAD

**Issue by chengshiding** [kernelhcy/gtkqq#36]
# ./autogen.sh
- aclocal
- autoconf
  configure.ac:37: error: possibly undefined macro: AC_CHECK_LIB
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
  configure.ac:71: error: possibly undefined macro: AC_DEFINE
  configure.ac:72: error: possibly undefined macro: AC_SUBST
  configure.ac:199: error: possibly undefined macro: AC_MSG_RESULT
  configure.ac:202: error: possibly undefined macro: AC_MSG_ERROR
- mkdir usr
  ++ pwd
- ./configure --enable-debug --prefix=/home/shiding/Downloads/kernelhcy-gtkqq-6a29155/usr
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... no
  checking for mawk... mawk
  checking whether make sets $(MAKE)... yes
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking for style of include used by make... GNU
  checking dependency style of gcc... gcc3
  checking dependency style of gcc... (cached) gcc3
  checking whether gcc and cc understand -c and -o together... yes
  checking build system type... i686-pc-linux-gnu
  checking host system type... i686-pc-linux-gnu
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... yes
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for ar... ar
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking for pthread_create in -lpthread... yes
  checking for compress in -lzlib... no
  checking arpa/inet.h usability... yes
  checking arpa/inet.h presence... yes
  checking for arpa/inet.h... yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking netdb.h usability... yes
  checking netdb.h presence... yes
  checking for netdb.h... yes
  checking netinet/in.h usability... yes
  checking netinet/in.h presence... yes
  checking for netinet/in.h... yes
  checking for stdint.h... (cached) yes
  checking for stdlib.h... (cached) yes
  checking for string.h... (cached) yes
  checking sys/ioctl.h usability... yes
  checking sys/ioctl.h presence... yes
  checking for sys/ioctl.h... yes
  checking sys/socket.h usability... yes
  checking sys/socket.h presence... yes
  checking for sys/socket.h... yes
  checking for unistd.h... (cached) yes
  checking zlib.h usability... no
  checking zlib.h presence... no
  checking for zlib.h... no
  ./configure: line 10956: syntax error near unexpected token `ZLIB,'
  ./configure: line 10956:`PKG_CHECK_MODULES(ZLIB, zlib >= 1.2,'
  系统是debian 6.0

**Comment by shwangdev** [comment]
这种问题，请google解决。

**Comment by ekd123** [comment]
apt-get install zlib-dev

**Comment by chengshiding** [comment]
解决了，是库缺少问题。

**Comment by chengshiding** [comment]
不过，这个gtkqq要求的gtk库比较高。
