### ISSUE TITLE
Looking forward implementation of "send file/send offline file".

### ISSUE THREAD

**Issue by xeow** [kernelhcy/gtkqq#37]
I think a QQ client under Linux with the capability of "send file/send offline file" would be possibly one of most desirable feature for Linux users' desperate requirement.

The old crap "linuxqq" or "libqq2010" which still developing either lacks this feature. I really hope "gtkqq" can accomplish the magnificent feat.

**Comment by shwangdev** [comment]
Cause the protocol of gtkqq is based on webqq hacking.

If web qq support feature of "send file/send offline file" , we might
shark the http package that webqq transferred and implement that
feature.

However, if webqq did not support this feature, we could not either.

On Sun, Dec 25, 2011 at 10:09 PM, xeow
reply@reply.github.com
wrote:

> I think a QQ client under Linux with the capability of "send file/send offline file" would be possibly one of most desirable feature for Linux users' desperate requirement.
> 
> The old crap "linuxqq" or "libqq2010" which still developing either lacks this feature. I really hope "gtkqq" can accomplish the magnificent feat.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/37

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@wxjeacen webqq 本来就支持离线文件传输的嘛

**Comment by shwangdev** [comment]
你没看懂我说的什么吧。

我是说如果web qq 支持离线文件，那么我们可以hack traffic来实现。

如果不支持，那我们也就没有办法实现。

On Tue, Dec 27, 2011 at 8:59 AM, billzt
reply@reply.github.com
wrote:

> @wxjeacen webqq 本来就支持离线文件传输的嘛
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/37#issuecomment-3277848

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com
