### ISSUE TITLE
消息盒子还有群消息不要声音~~！

### ISSUE THREAD

**Issue by awaysoft** [kernelhcy/gtkqq#38]
啊，我60多个群，一打开这软件，就吵死。。。完全没法用了，一直一直在叫。。。。

**Comment by mathslinux** [comment]
@awaysoft  我是这样处理的, 有消息就播放声音.  希望能描述一下 winqq是怎么处理这类消息的, 我看看会不会效果更好.

静音功能稍候献上.

**Comment by awaysoft** [comment]
WinQQ的做法是：如果那个群有消息未读或者群已经打开，那么就不再提示那个群，而不是每个消息都提示，好友的消息倒是会每次都提示。

**Comment by mathslinux** [comment]
@awaysoft finish it, please help test it.
@wxjeacen @kernelhcy Code finished, merge it, and help code review

**Comment by kernelhcy** [comment]
@mathslinux Good Job!

**Comment by awaysoft** [comment]
感觉没啥区别啊，还是一条消息一个声音~~~~~而且，感觉接收群消息好慢，没有WebQQ快啊。。。

**Comment by mathslinux** [comment]
@awaysoft 我测试是没有问题的, 你用最新的 git?
对于 qq群的问题, 准备实现本地的保存, 这样会快一些.

**Comment by shwangdev** [comment]
hmm, 我最近公司项目忙，木得时间搞这个。

本地可以cache, 但是后台要有机制做update.

2011/12/29 mathslinux
reply@reply.github.com:

> @awaysoft 我测试是没有问题的, 你用最新的 git?
> 对于 qq群的问题, 准备实现本地的保存, 这样会快一些.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelhcy/gtkqq/issues/38#issuecomment-3299516

## 

Best Regards,

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com

**Comment by tao-bioinfo** [comment]
@mathslinux 你好！可否在issue里简单的描述一下，新加入的 mute 是什么样的功能？正如前面几楼说的功能吗？

**Comment by mathslinux** [comment]
@billzt 是这样的, 登录qq以后, 右键单击 qq的托盘图标, 不是有一个mute吗? 选上这个就静音了. 把钩去掉就又有声音了. 
选完之后我是保存在数据库里面的, 下次登录直接从数据库判断是否静音. 我简单的测试了没有问题, 不过一平时一般是开着声音的.

**Comment by tao-bioinfo** [comment]
@mathslinux 原来如此，就是加了一个总开关。声音的问题感觉关系不大

**Comment by awaysoft** [comment]
@mathslinux 是的，最新的，mute也试了，没啥效果，声音还在。。。。

**Comment by mathslinux** [comment]
@awaysoft 不会阿, 我重新 clone 了master, 然后把数据库删除了测试了一下, 其他人 @billzt 帮忙看看.

**Comment by awaysoft** [comment]
@mathslinux 删除所有数据重新安装。。。成功段错误了。。。。完全打不开了。。

**Comment by mathslinux** [comment]
@awaysoft 不是吧, 你把 ~/.gtkqq 整个目录删除看看

**Comment by tao-bioinfo** [comment]
@mathslinux @awaysoft 我这儿测试已经成功。准备元旦时放出新的ppa

**Comment by tao-bioinfo** [comment]
@mathslinux 不过既然已经出了这么一个选项，能不能把“System setting”这个界面做出来？把选项放到里面吧！unity 桌面是禁用托盘图标的

**Comment by awaysoft** [comment]
@mathslinux 是的，就是删除了这个目录之后出现的。。。。

**Comment by awaysoft** [comment]
@billzt 放个rpm把~

**Comment by awaysoft** [comment]
@mathslinux 目前消息接收还是不稳定，webqq本身就存在这个问题，不知道有好的解决方法木。。。。

**Comment by tao-bioinfo** [comment]
@awaysoft 可是我不会做 rpm 啊。之前学deb打包已经把我折腾倒了
