### ISSUE TITLE
紧急bug：请修改qqtypes.c的qq_info_new函数！

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#39]
在 Ubuntu 12.04 上编译时发生错误：

qqtypes.c: In function 'qq_info_new':
qqtypes.c:26:5: error: 'g_mutex_new' is deprecated (declared at /usr/include/glib-2.0/glib/deprecated/gthread.h:271) [-Werror=deprecated-declarations]
qqtypes.c: In function 'qq_info_free':
qqtypes.c:94:5: error: 'g_mutex_free' is deprecated (declared at /usr/include/glib-2.0/glib/deprecated/gthread.h:273) [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors

大概原因：g_mutex_new()函数在新版系统中已被废弃
http://developer.gnome.org/glib/2.31/glib-Deprecated-Thread-APIs.html
请换成别的吧，离Ubuntu12.04发布也不到五个月时间了～

**Comment by shwangdev** [comment]
Ub12.04只是beta版，目前完全没有必要去support,谁知道他一会又改个什么东西。

**Comment by tao-bioinfo** [comment]
@wxjeacen 大哥，看到我发的链接网址没？这是gnome的函数库啊，是上游的决定，基本上已经定了。我说的ubuntu12.04不过是举一个例子而已。而且这已经是编译的error了，不是warning，还是修正一下比较好

**Comment by kernelhcy** [comment]
这个并不算是一个bug。因为gtkqq开发所用的gtk版本中，g_mutex_new还是可以使用的。建议你去掉-Werror参数再编译。如果gtkqq迁移到更高版本的gtk上，这个问题自然会解决。

**Comment by tao-bioinfo** [comment]
@kernelhcy 也行，只要不影响用户使用，我试试看

**Comment by ekd123** [comment]
@kernelhcy Use g_mutex_init(GMutex *mutex) instead

**Comment by tao-bioinfo** [comment]
@kernelhcy @ekd123 @wxjeacen 要是g_mutex_init(GMutex *mutex) 可行的话，还是修正下为好

**Comment by kernelhcy** [comment]
@billzt g_mutex_init是在glib2.32中引入的。当前稳定版的glib是2.30，还没有g_mutex_init。gtkqq不考虑使用开发版的glib。因此，目前不会引入g_mutex_init。

**Comment by tao-bioinfo** [comment]
@kernelhcy 只要能够通过编译，不影响最终用户使用，用什么函数都行。

**Comment by ekd123** [comment]
@kernelhcy 用#ifdef啊！
#ifdef g_mutex_init
...
#else
...
#endif
