### ISSUE TITLE
强制类型安全检查时编译失败

### ISSUE THREAD

**Issue by leaeasy** [kernelhcy/gtkqq#4]
# Index: gtkqq-0+gitf39d6202/src/libqq/url.c

--- gtkqq-0+gitf39d6202.orig/src/libqq/url.c    2011-11-25 18:17:35.537317364 +0800
+++ gtkqq-0+gitf39d6202/src/libqq/url.c 2011-11-25 18:19:26.869320170 +0800
@@ -387,7 +387,7 @@
                     }
                 }else{
                     g_debug("More chunks... Begin %d len %d %s(%s, %d)"
-                                        , chunkbegin, data -> len
-                                        , chunkbegin, (int)data -> len
                                       , data -> str + chunkbegin
                                       , **FILE**, **LINE**);
                   break;

**Comment by shwangdev** [comment]
It was ambiguous for compiler. Cause the compile might not know what you want to style change.
I mean int for what, data or data->len? data is a pointer , data->len should be int.

**Comment by leaeasy** [comment]
这个是debian上编译器强制类型安全检查出的问题，在别的地方我编译是通过的，int是指data->len

**Comment by kernelhcy** [comment]
just close it
