### ISSUE TITLE
bug：没有勾选记住密码，下次打开后，密码还在

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#41]
具体重现方法是这样：

先用帐号 A 登陆，不保存密码。然后退出

再用帐号B登陆，也不保存密码。然后退出

第三次，可以从下拉列表里面选择帐号A或B了，但这时密码会自动填充进去（太智能了）。这样，“不保存密码”那个选项就形同虚设了。

**Comment by mathslinux** [comment]
@billzt fixed it.

**Comment by tao-bioinfo** [comment]
@mathslinux very good! thank you
