### ISSUE TITLE
debian下运行时段错误

### ISSUE THREAD

**Issue by chengshiding** [kernelhcy/gtkqq#45]
RT，debian 是testing，桌面是xfce4。
[debian:gui]$./gtkqq 
Last datebase version is 1002. (dao.c, 84)

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion `GDK_IS_PIXBUF (pixbuf)' failed

(lt-gtkqq:30817): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion `GDK_IS_PIXBUF (pixbuf)' failed
段错误
[debian:gui]$

**Comment by Juansheng** [comment]
嗯，一样的段错误，只不过桌面是 gnome-shell。但我怀疑是 debian 自身库的问题，因为别的 gtk 程序（比如 gVim）退出时会有一堆出错信息，但还不至于 Segmentation fault。

**Comment by chengshiding** [comment]
不知道是不是某些库没安装全
于 2012年01月05日 21:44, Jie W. 写道:

**Comment by ekd123** [comment]
Arch + GNOME 3 没问题。

**Comment by Juansheng** [comment]
几次 apt 系统升级之后，段错误消失，可以关了这个 issue。测试了下，完美运行。:D
