### ISSUE TITLE
建议把文字输入框调小一点

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#46]
ubuntu下使用 --enable-unity 编译，输入框太大，导致信息显示框比较小。即使用户自行调整，效果仍然不明显。建议把 --enable-unity 编译时文字输入框的高度适当调低

**Comment by mathslinux** [comment]
@billzt 这个等到下一个 plan, 我会将它移植到 gtk3, 然后就没有这个问题了.

**Comment by tao-bioinfo** [comment]
@mathslinux 这个问题也不着急，先关闭了
