### ISSUE TITLE
报告几个段错误 bug

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#47]
DEBUG : Get face image of 3265364823!(qqimg.c, 45)
DEBUG : Content-Length: 4854.(url.c, 326)
DEBUG : Content-Length: 12053.(url.c, 326)
段错误

DEBUG : GQQConfig getter: mute (gqqconfig.c, 115)
DEBUG : poll.(qqpoll.c, 305)

(gtkqq:17971): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `(null)'
段错误

来自部分网友测试的结果

**Comment by mathslinux** [comment]
@billzt 我会写一篇how to debug的文章, 让有能力的童鞋帮忙debug

**Comment by kernelhcy** [comment]
@mathslinux 给力！

**Comment by mathslinux** [comment]
@billzt https://github.com/kernelhcy/gtkqq/wiki/How-to-debug 未完待续.
