### ISSUE TITLE
gtkqq开发、用户常规讨论邮件列表邀请您

### ISSUE THREAD

**Issue by chengshiding** [kernelhcy/gtkqq#48]
订阅有两种办法：
1、登录  https://groups.google.com/group/gtkqq-dev ，然后，点击加入或退出就可以订阅或退出该列表了。
2、如果上不来上面的网站，可以邮件订阅的。
      订阅：发邮件到 ：gtkqq-dev+subscribe@googlegroups.com
      退订：发邮件到：gtkqq-dev+unsubscribe@googlegroups.com
3、欢迎所有支持、对gtkqq的用户加入，尤其是该项目维护者！~~

**Comment by kernelhcy** [comment]
Great！

**Comment by chengshiding** [comment]
现在里面认还少，继续推广之。。。

**Comment by chengshiding** [comment]
希望把上面的内容加到公告里面好吗？这样，看到的人会多些。

**Comment by ekd123** [comment]
无法加入， Joining via email is disabled for this group.

**Comment by ekd123** [comment]
嘛，web界面也无法……因为我用的不是gmail
