### ISSUE TITLE
消息机制

### ISSUE THREAD

**Issue by gracegreen** [kernelhcy/gtkqq#51]
作者们好，今天试用了gtkqq，还可以，就一点建议，状态栏的效果不是太好，而且在Unity里已经禁用托盘图标，而是把通讯工具全都放在“消息”那个图标下，用的indicator机制，作者可以考虑下这种方案，并不是很复杂。

**Comment by kernelhcy** [comment]
我们会认真考虑并尽快加上去。非常感谢你的建议～^v^

**Comment by tao-bioinfo** [comment]
@gracegreen 其实代码里面已经有 libnotify 了，只是现在被注释掉了，以后肯定会打开的。现在的关键是要修复一些崩溃问题，因为好像还是有很多人无法登陆

**Comment by ekd123** [comment]
@billzt @kernelhcy 应该把bug修复和新特性都分开的。应该是这样的，修复问题应该branch一个新分支，叫做 issueXXXX，修复完后再merge回develop。如果是开发者自己检测出来的bug，可以不这么干，有issue的话还是这么弄比较好吧。

**Comment by kernelhcy** [comment]
@ekd123 issue分支可以直接由committer自己管理。分支太多也不好。
