### ISSUE TITLE
无法通过VPN登录

### ISSUE THREAD

**Issue by windwhinny** [kernelhcy/gtkqq#52]
如题，我使用的是https://www.runoz.us VPN，每次登录的时候都会要求输入验证码，但还是不能登录

wind@wind-netbook:~/workspace/gtkqq$ /usr/bin/gtkqq
DEBUG : Open db connection to /home/wind/.gtkqq/gtkqq.db (dao.c, 168)
DEBUG : Create all tables (dao.c, 147)
Last datebase version is -1. (dao.c, 84)
Update datebase from version 1001 to version 1002 (dao.c, 39)
DEBUG : GQQConfig setter: info (gqqconfig.c, 156)
DEBUG : Start Send main loop...(msgloop.c, 36)
DEBUG : Start Get informain main loop...(msgloop.c, 36)
DEBUG : Start Get Number and face images main loop...(msgloop.c, 36)
DEBUG : Start login... qqnum: 331843672, status: online (loginpanel.c, 344)
DEBUG : Run login state machine...(loginpanel.c, 347)
DEBUG : Check veriry code...(qqlogin.c, 45)
DEBUG : GQQConfig setter: qqnum (gqqconfig.c, 156)
DEBUG : GQQConfig setter: passwd (gqqconfig.c, 156)
DEBUG : GQQConfig setter: status (gqqconfig.c, 156)
DEBUG : GQQConfig setter: rempw (gqqconfig.c, 156)
DEBUG : The message body is chunked.(url.c, 337)
DEBUG : check vc return: ptui_checkVC('1','434c340aa13a36fd843ab9cf2f5fb967699de5178fa0a2c3');(qqlogin.c, 109)
DEBUG : We need verify code image! vc_type: 434c340aa13a36fd843ab9cf2f5fb967699de5178fa0a2c3 (qqlogin.c, 145)
DEBUG : Get verify code image...(qqlogin.c, 876)
DEBUG : Content-Length: 2803.(url.c, 326)
DEBUG : vc content type: image/jpeg(qqlogin.c, 218)
DEBUG : Verify code image file type: jpeg len 2803 (qqlogin.c, 230)
DEBUG : Create image file : /home/wind/.gtkqq/verifycode.jpeg (qqutils.c, 33)
DEBUG : Get version...(qqlogin.c, 671)
DEBUG : Content-Length: 22.(url.c, 326)
DEBUG : Version: 201112282038(qqlogin.c, 293)
DEBUG : Login...(qqlogin.c, 685)
DEBUG : Get ptcz and skey...(qqlogin.c, 688)
DEBUG : The message body is chunked.(url.c, 337)
*\* WARNING *\* : Wrong input!(qqlogin.c, 450)
*\* WARNING *\* : Login error! Error occured! Please try again. (loginpanel.c, 122)
DEBUG : Login error... (loginpanel.c, 236)
DEBUG : Show login panel.(loginpanel.c, 239)

**Comment by mathslinux** [comment]
@windwhinny 你有没有 ssh, 用ssh fuckgfw 试试. 没有vpn环境无法测试. 不过验证登录好像一直有问题.

**Comment by kernelhcy** [comment]
目前暂不支持验证码。输入验证码也没用。这个在协议上还没有解决。
