### ISSUE TITLE
发现一个托盘的BUG

### ISSUE THREAD

**Issue by windwhinny** [kernelhcy/gtkqq#69]
当鼠标悬停在托盘上，并出现tooltip时，终端会出现以下4个警告：

(gtkqq:11026): Gdk-CRITICAL **: IA__gdk_window_get_root_coords: assertion `GDK_IS_WINDOW (window)' failed

(gtkqq:11026): Gdk-CRITICAL **: IA__gdk_window_get_root_coords: assertion `GDK_IS_WINDOW (window)' failed

(gtkqq:11026): Gdk-CRITICAL **: IA__gdk_window_get_root_coords: assertion `GDK_IS_WINDOW (window)' failed

(gtkqq:11026): Gdk-CRITICAL **: IA__gdk_window_get_root_coords: assertion `GDK_IS_WINDOW (window)' failed

**Comment by shwangdev** [comment]
不影响function
