### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#7]
运行 ./autogen.sh，前面基本正常，最后报错信息：

configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

怎么解决？

**Comment by shwangdev** [comment]
把所有的log都贴上来。
On Nov 30, 2011 12:39 PM, "billzt" <
reply@reply.github.com>
wrote:

**Comment by tao-bioinfo** [comment]
全部信息：
$ ./autogen.sh 
- aclocal
- autoconf
  configure.ac:20: error: possibly undefined macro: AC_PROG_LIBTOOL
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
- mkdir usr
  ++ pwd
- ./configure --enable-debug --prefix=/home/bill/software/gtkqq/20111130/usr/
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... no
  checking for mawk... mawk
  checking whether make sets $(MAKE)... yes
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking for style of include used by make... GNU
  checking dependency style of gcc... gcc3
  checking dependency style of gcc... (cached) gcc3
  checking whether gcc and cc understand -c and -o together... yes
  ./configure: line 4040: LT_INIT: command not found
  ./configure: line 4041: AC_PROG_LIBTOOL: command not found
  checking for pthread_create in -lpthread... yes
  checking for compress in -lzlib... no
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking arpa/inet.h usability... yes
  checking arpa/inet.h presence... yes
  checking for arpa/inet.h... yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking netdb.h usability... yes
  checking netdb.h presence... yes
  checking for netdb.h... yes
  checking netinet/in.h usability... yes
  checking netinet/in.h presence... yes
  checking for netinet/in.h... yes
  checking for stdint.h... (cached) yes
  checking for stdlib.h... (cached) yes
  checking for string.h... (cached) yes
  checking sys/ioctl.h usability... yes
  checking sys/ioctl.h presence... yes
  checking for sys/ioctl.h... yes
  checking sys/socket.h usability... yes
  checking sys/socket.h presence... yes
  checking for sys/socket.h... yes
  checking for unistd.h... (cached) yes
  checking zlib.h usability... yes
  checking zlib.h presence... yes
  checking for zlib.h... yes
  checking for pkg-config... /usr/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  checking for ZLIB... yes
  checking for GTK... yes
  checking for GLIB... yes
  checking for GTHREAD... yes
  checking for SQLITE3... yes
  checking for GLIB2... yes
  checking for GOBJECT2... yes
  checking for pid_t... yes
  checking vfork.h usability... no
  checking vfork.h presence... no
  checking for vfork.h... no
  checking for fork... yes
  checking for vfork... yes
  checking for working fork... yes
  checking for working vfork... (cached) yes
  checking for stdlib.h... (cached) yes
  checking for GNU libc compatible malloc... yes
  checking for bzero... yes
  checking for gethostbyname... yes
  checking for memset... yes
  checking for mkdir... yes
  checking for select... yes
  checking for socket... yes
  checking for strstr... yes
  checking for strtol... yes
  checking for inet_ntoa... yes
  configure: creating ./config.status
  config.status: error: cannot find input file: `Makefile.in'

**Comment by shwangdev** [comment]
./configure: line 4040: LT_INIT: command not found
./configure: line 4041: AC_PROG_LIBTOOL: command not found*
*
2011/11/30 billzt <
reply@reply.github.com

> ./configure: line 4040: LT_INIT: command not found
> ./configure: line 4041: AC_PROG_LIBTOOL: command not found

## 

**
*

Best Regards,
**

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com wxjeacen@gmail.com

*

**Comment by shwangdev** [comment]
*可能你要更新你的libtools
*
2011/11/30 Xiang Wang wxjeacen@gmail.com

> ./configure: line 4040: LT_INIT: command not found
> ./configure: line 4041: AC_PROG_LIBTOOL: command not found*
> *
> 2011/11/30 billzt <
> reply@reply.github.com
> 
> > ./configure: line 4040: LT_INIT: command not found
> > ./configure: line 4041: AC_PROG_LIBTOOL: command not found
> 
> ## 
> 
> **
> *
> 
> Best Regards,
> **
> 
> Devil Wang| Engineer of Linux
> 
> Gtalk: wxjeacen AT gmail DOT com wxjeacen@gmail.com
> 
> *

## 

**
*

Best Regards,
**

Devil Wang| Engineer of Linux

Gtalk: wxjeacen AT gmail DOT com wxjeacen@gmail.com

*

**Comment by tao-bioinfo** [comment]
能说下怎么更新吗？

**Comment by tao-bioinfo** [comment]
安装 libtool 已解决，谢谢！
