### ISSUE TITLE
dev 分支里面的 --enable-debug 编译选项没有了？

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#72]
我今天编译时发现它不认 --enable-debug 选项了。在 configure.ac 文件里面也没有找到 --enable-debug 选项，最后编译出来的程序也没有 debug 功能。

**Comment by crab2313** [comment]
debug 已经默认加进去了， 你看新加的命令行参数

**Comment by tao-bioinfo** [comment]
@crab2313 哦，请问下该怎么看？或者说怎么运行调试？

**Comment by crab2313** [comment]
命令行 gtkqq -d 就行了

**Comment by tao-bioinfo** [comment]
@crab2313 好的，明白了，多谢！
