### ISSUE TITLE
Failed to Run

### ISSUE THREAD

**Issue by ekd123** [kernelhcy/gtkqq#8]
`$ gtkqq

*\* ERROR **: Create config dir /root/.gtkqq/ error!(gqqconfig.c, 246)
zsh: trace trap  gtkqq
`

Why don't use `g_get_home_dir()`?

**Comment by shwangdev** [comment]
Change it later.
On Dec 1, 2011 9:39 PM, "Mike Manilone" <
reply@reply.github.com>
wrote:

**Comment by kernelhcy** [comment]
close
