### ISSUE TITLE
建议加入消息通知功能

### ISSUE THREAD

**Issue by tao-bioinfo** [kernelhcy/gtkqq#9]
其实我并没有运行成功（已通过编译，但无法运行），所以尚且不知道是否有消息通知功能。但看到 todo 文件里面 done 和 todo 列表里都没有列出来。这个功能应该也不难实现，随便参考某个IM的代码，把系统内置的消息通知功能带出来就OK了。基本上，todo里面的功能再加上该功能，这个QQ就很完美了。

**Comment by shwangdev** [comment]
我们有XiaoX提示的
On Dec 2, 2011 1:30 PM, "billzt" <
reply@reply.github.com>
wrote:

**Comment by tao-bioinfo** [comment]
那就好，希望尽快完善todo功能

**Comment by mathslinux** [comment]
相关代码我已经加进去了, 稍等提交.

**Comment by tao-bioinfo** [comment]
很好，既然这个问题不存在，我可以close了

**Comment by shwangdev** [comment]
Do it
On Dec 2, 2011 2:35 PM, "billzt" <
reply@reply.github.com>
wrote:
