### ISSUE TITLE
使用socket5代理导致频繁崩溃

### ISSUE THREAD

**Issue by renothing** [kernelhcy/gtkqq#94]
Last datebase version is 1002. (dao.c, 84)

(gtkqq:4552): Gtk-CRITICAL *_: IA__gtk_combo_box_set_entry_text_column: assertion `model == NULL || text_column < gtk_tree_model_get_n_columns (model)' failed
*_ WARNING *\* : Resoponse status is NOT 200, but 500 (qqmanageinfo.c, 489)
*\* WARNING *\* : Invalid json value...(json.c,433)
*\* WARNING *\* : No TreeMap for 1623747527. We may need add it..(buddytree.c, 581)
*\* WARNING *\* : No TreeMap for 3163669843. We may need add it..(buddytree.c, 581)
*\* WARNING *\* : No TreeMap for 2431409928. We may need add it..(buddytree.c, 581)
*\* WARNING *\* : No TreeMap for 3650254803. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 877594215. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 3864526741. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 1252726938. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 3848709400. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 1744539613. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 595954186. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : json_parser_document: syntax error. (qqmanageinfo.c, 97)
*\* WARNING *\* : No TreeMap for 1623747527. We may need add it..(buddytree.c, 581)
*\* WARNING *\* : No TreeMap for 3163669843. We may need add it..(buddytree.c, 581)

(gtkqq:4552): GLib-GObject-WARNING *_: g_object_set_valist: object class `QQChatWindow' has no property named`status'
*_ WARNING *\* : No TreeMap for 3650254803. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 877594215. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 3864526741. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 1252726938. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 3848709400. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 2431409928. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 1744539613. We may need add it..(buddytree.c, 583)
*\* WARNING *\* : No TreeMap for 595954186. We may need add it..(buddytree.c, 583)

*\* ERROR **: Got error response from SOCKS server: 1 ...(qqproxy.c,883)
Trace/breakpoint tra

**Comment by shwangdev** [comment]
Resoponse status is NOT 200, but 500

你的代理根本不通。

2012/3/2 renothing <
reply@reply.github.com

> Resoponse status is NOT 200, but 500

**Comment by renothing** [comment]
不至于了。。。。我其他程序也用的同样代理，ok的。代理是内网的

**Comment by y-usuzumi** [comment]
gtkqq团队对待issue的态度让我无语。

不管代理通不通，崩溃就是严重的Bug。

**Comment by shwangdev** [comment]
能不能提供core dump?
